import { useState, useCallback, useRef } from "react";
import type { Editor as TiptapEditor } from "@tiptap/core";
import {
  withApcore,
  type Registry,
  type Executor,
  type ApcoreResult,
} from "tiptap-apcore";
import Editor from "./components/Editor";
import ToolPanel from "./components/ToolPanel";
import type { LogEntry } from "./components/ToolPanel";
import AclSwitcher from "./components/AclSwitcher";
import ChatPanel from "./components/ChatPanel";

export default function App() {
  const [role, setRole] = useState<"readonly" | "editor" | "admin">("admin");
  const [registry, setRegistry] = useState<Registry | null>(null);
  const [executor, setExecutor] = useState<Executor | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [showConfirm, setShowConfirm] = useState(false);
  const editorRef = useRef<TiptapEditor | null>(null);
  const apcoreRef = useRef<ApcoreResult | null>(null);

  const addLog = useCallback((entry: LogEntry) => {
    setLogs((prev) => [entry, ...prev].slice(0, 100));
  }, []);

  /** Initialize or re-initialize APCore when editor is ready or role changes */
  const initApcore = useCallback(
    (editor: TiptapEditor, currentRole: "readonly" | "editor" | "admin") => {
      try {
        const result = withApcore(editor, { acl: { role: currentRole } });
        apcoreRef.current = result;
        setRegistry(result.registry);
        setExecutor(result.executor);
        addLog({
          type: "info",
          message: `APCore initialized: role=${currentRole}, ${result.registry.list().length} modules`,
          timestamp: Date.now(),
        });
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        addLog({
          type: "error",
          message: `APCore init failed: ${msg}`,
          timestamp: Date.now(),
        });
      }
    },
    [addLog],
  );

  const handleEditorReady = useCallback(
    (editor: TiptapEditor) => {
      editorRef.current = editor;
      initApcore(editor, role);
    },
    [role, initApcore],
  );

  const handleRoleChange = useCallback(
    (newRole: "readonly" | "editor" | "admin") => {
      setRole(newRole);
      if (editorRef.current) {
        initApcore(editorRef.current, newRole);
      }
    },
    [initApcore],
  );

  // ---- Demo scenario handlers ----

  async function demoInsertHeading() {
    if (!executor) return;
    try {
      // First toggle heading
      await executor.call("tiptap.format.toggleHeading", { level: 1 });
      addLog({
        type: "success",
        message: "tiptap.format.toggleHeading({ level: 1 })",
        timestamp: Date.now(),
      });

      // Then insert content
      await executor.call("tiptap.content.insertContent", {
        value: "APCore lets AI directly control your editor",
      });
      addLog({
        type: "success",
        message:
          'tiptap.content.insertContent({ value: "APCore lets AI directly control your editor" })',
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  async function demoWriteParagraph() {
    if (!executor) return;
    try {
      await executor.call("tiptap.content.insertContent", {
        value:
          "<p>This content was automatically generated by AI using the APCore module. APCore enables AI to safely control your editor, with every action annotated and subject to permission controls.</p>",
      });
      addLog({
        type: "success",
        message: "tiptap.content.insertContent (paragraph)",
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  async function demoFormat() {
    if (!executor) return;
    try {
      // Select all content
      await executor.call("tiptap.selection.selectAll", {});
      addLog({
        type: "success",
        message: "tiptap.selection.selectAll()",
        timestamp: Date.now(),
      });

      // Toggle bold on selection
      await executor.call("tiptap.format.toggleBold", {});
      addLog({
        type: "success",
        message: "tiptap.format.toggleBold()",
        timestamp: Date.now(),
      });

      // Toggle italic
      await executor.call("tiptap.format.toggleItalic", {});
      addLog({
        type: "success",
        message: "tiptap.format.toggleItalic()",
        timestamp: Date.now(),
      });

      // Toggle bullet list
      await executor.call("tiptap.format.toggleBulletList", {});
      addLog({
        type: "success",
        message: "tiptap.format.toggleBulletList()",
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  function demoClearDocument() {
    // Show confirmation dialog -- APCore intercepts destructive ops
    setShowConfirm(true);
    addLog({
      type: "info",
      message:
        "Destructive operation intercepted! Showing confirmation dialog...",
      timestamp: Date.now(),
    });
  }

  async function confirmClear() {
    setShowConfirm(false);
    if (!executor) return;
    try {
      await executor.call("tiptap.destructive.clearContent", {});
      addLog({
        type: "success",
        message: "tiptap.destructive.clearContent() -- confirmed by user",
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  function cancelClear() {
    setShowConfirm(false);
    addLog({
      type: "info",
      message: "Destructive operation cancelled by user",
      timestamp: Date.now(),
    });
  }

  // ---- Chat integration helpers ----

  function getEditorHtml(): string {
    if (editorRef.current) {
      return editorRef.current.getHTML();
    }
    return "";
  }

  const handleEditorUpdate = useCallback(
    async (html: string) => {
      if (!executor) return;
      try {
        await executor.call("tiptap.destructive.setContent", { value: html });
        addLog({
          type: "info",
          message: "Editor updated from AI response",
          timestamp: Date.now(),
        });
      } catch (err: unknown) {
        // If setContent fails via executor (e.g. ACL), fall back to direct editor update
        if (editorRef.current) {
          editorRef.current.commands.setContent(html);
          addLog({
            type: "info",
            message: "Editor updated from AI response (direct)",
            timestamp: Date.now(),
          });
        }
      }
    },
    [executor, addLog],
  );

  return (
    <>
      <header className="app-header">
        <h1>
          tiptap-<span>apcore</span> Demo
        </h1>
        <p>Let AI safely control your TipTap editor</p>
      </header>

      <div className="app-layout">
        {/* Left: ACL + Module panel */}
        <div>
          <AclSwitcher role={role} onChange={handleRoleChange} />
          <ToolPanel registry={registry} executor={executor} onLog={addLog} />
        </div>

        {/* Center: Editor */}
        <Editor onEditorReady={handleEditorReady} />

        {/* Right-1: Chat Panel */}
        <ChatPanel
          getEditorHtml={getEditorHtml}
          role={role}
          onEditorUpdate={handleEditorUpdate}
          onLog={addLog}
        />

        {/* Right-2: Demo scenarios + Log */}
        <div className="demo-panel">
          <div className="card">
            <h2>Demo Scenarios</h2>
            <div className="demo-buttons">
              <button className="demo-btn" onClick={demoInsertHeading}>
                <div className="demo-btn-title">AI Insert Title</div>
                <div className="demo-btn-desc">
                  toggleHeading + insertContent
                </div>
              </button>

              <button className="demo-btn" onClick={demoWriteParagraph}>
                <div className="demo-btn-title">AI Write a Paragraph</div>
                <div className="demo-btn-desc">
                  insertContent with HTML paragraph
                </div>
              </button>

              <button className="demo-btn" onClick={demoFormat}>
                <div className="demo-btn-title">AI Formatting</div>
                <div className="demo-btn-desc">
                  selectAll + bold + italic + bulletList
                </div>
              </button>

              <button
                className="demo-btn danger"
                onClick={demoClearDocument}
              >
                <div className="demo-btn-title">AI Clear Document</div>
                <div className="demo-btn-desc">
                  clearContent (requires confirmation)
                </div>
              </button>
            </div>
          </div>

          <div className="card log-panel">
            <h2>
              Output Log
              {logs.length > 0 && (
                <button
                  className="log-clear-btn"
                  onClick={() => setLogs([])}
                >
                  Clear
                </button>
              )}
            </h2>
            <div className="log-entries">
              {logs.length === 0 && (
                <div
                  style={{
                    fontSize: 12,
                    color: "var(--text-secondary)",
                    padding: 4,
                  }}
                >
                  No logs yet. Try a demo scenario or chat with AI.
                </div>
              )}
              {logs.map((entry, i) => (
                <div key={i} className={`log-entry ${entry.type}`}>
                  <span style={{ opacity: 0.6 }}>
                    {new Date(entry.timestamp).toLocaleTimeString()}
                  </span>{" "}
                  {entry.message}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Confirmation Dialog */}
      {showConfirm && (
        <div className="dialog-overlay" onClick={cancelClear}>
          <div className="dialog-box" onClick={(e) => e.stopPropagation()}>
            <h3>Confirm Clear?</h3>
            <p>
              APCore has intercepted a destructive action. AI is attempting to clear the entire document.
              <br />
              This action is marked as <code>destructive: true</code> and{" "}
              <code>requires_approval: true</code>.
            </p>
            <div className="dialog-actions">
              <button className="btn-cancel" onClick={cancelClear}>
                Cancel
              </button>
              <button className="btn-confirm" onClick={confirmClear}>
                Confirm Clear
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
