services:
  frontend:
    build:
      context: ..
      dockerfile: demo/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/demo/frontend/src
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001

  backend:
    build:
      context: ..
      dockerfile: demo/Dockerfile.backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - PORT=3001
